/**
 * Genera `src/schemaSql.generated.ts` desde `db/schema.sql` para que Vercel/serverless
 * no dependa de leer el .sql en runtime. Parte en varias sentencias (algunos proxies
 * no aceptan múltiples comandos en un solo round-trip).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const schemaPath = path.join(__dirname, "..", "db", "schema.sql");
const outPath = path.join(__dirname, "..", "src", "schemaSql.generated.ts");

/** Quita comentarios `--` de línea para que el splitter vea `;` → `CREATE` sin bloques `--` intermedios. */
function stripLineComments(sql) {
  return sql.replace(/--[^\n]*/g, "");
}

function splitSchemaStatements(sql) {
  return sql
    .trim()
    .split(/(?<=;)\s*(?=(?:CREATE|INSERT|SELECT|ALTER)\b)/i)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

const rawSql = fs.readFileSync(schemaPath, "utf8");
const statements = splitSchemaStatements(stripLineComments(rawSql));
const body = `/* eslint-disable */\n/** Auto-generated by scripts/embed-schema.mjs from db/schema.sql. Do not edit. */\nexport const IPC_SCHEMA_STATEMENTS = ${JSON.stringify(statements)} as const;\n`;
fs.writeFileSync(outPath, body, "utf8");
console.log("[embed-schema] wrote", outPath, `(${statements.length} statements)`);
