/**
 * Genera `src/schemaSql.generated.ts` desde `db/schema.sql` para que Vercel/serverless
 * no dependa de leer el .sql en runtime (rutas del bundle vs cwd).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const schemaPath = path.join(__dirname, "..", "db", "schema.sql");
const outPath = path.join(__dirname, "..", "src", "schemaSql.generated.ts");

const sql = fs.readFileSync(schemaPath, "utf8");
const body = `/* eslint-disable */\n/** Auto-generated by scripts/embed-schema.mjs from db/schema.sql. Do not edit. */\nexport const IPC_SCHEMA_SQL = ${JSON.stringify(sql)};\n`;
fs.writeFileSync(outPath, body, "utf8");
console.log("[embed-schema] wrote", outPath);
